<template>
<h1>Introduction</h1>
<p>In this book, I present one fundamental idea. &nbsp;Yet it is an idea so powerful that, if fully embraced, it radically alters the way we see the world. &nbsp;It changes how we view each other and how we treat one another. It shakes up our conceptions of the good society and of good social policy. It makes us better people, removes impediments to our own happiness, and increases the joy we find in life. &nbsp;</p>
<p>It is an idea based in science and reason, requiring no leaps of faith. It is an idea whose origins date back over three millennia, and at the same time is rooted in modern scientific discovery. &nbsp;It is not an easy idea. &nbsp;It requires abandoning a worldview that we probably have never questioned, a worldview that we take for granted, a worldview that affects our actions on a daily basis.</p>
<p>What is this radical yet ancient idea? It is simply this: we have no free will. The universe is a web of causation dating back to the beginning of time. Our actions are a part of this web. Although we feel that we are making decisions on the basis of free will, this is just an illusion. &nbsp;We could not have acted differently than we did.</p>
<p>Consider the case of Charles Whitman. &nbsp;Accounts describe Whitman as intelligent, attractive, a family man and an ex-Marine. &nbsp; In August 1966, after killing his mother and wife, Whitman climbed the tower at the University of Texas and began shooting with a hunting rifle. &nbsp;In all, he killed 13 people and injured over 30. &nbsp;Here is an account by the neuroscientist Robert Sapolsky:</p>
<p>Whitman was literally an Eagle Scout and a childhood choirboy, a happily married engineering major with an IQ in the 99th percentile. &nbsp;In the prior year he had seen doctors, complaining of severe headaches and violent impulses (e.g., to shoot people from the campus tower). &nbsp; He left notes by the bodies of his wife and his mother, proclaiming love and puzzlement at his actions: “I cannot rationaly [sic] pinpoint any specific reason for killing her,” and “let there be no doubt in your mind that I loved this woman with all my heart.” &nbsp;His suicide note requested an autopsy of his brain, and that any money he had be given to a mental health foundation. &nbsp;The autopsy proved his intuition correct – Whitman had a glioblastoma tumor pressing on his amygdala.&nbsp;
  <a href="#_ftn1" name="_ftnref1" title="">[1]</a>
</p>
<p>The amygdala is the part of the brain most responsible for aggression. &nbsp;Whitman, because he was killed at the scene, never had to face a criminal judgment. &nbsp;Experts disagree on the role of the malignant tumor in influencing Whitman’s actions. &nbsp;There were other factors in Whitman’s life that could have influenced his behavior or interacted with the tumor. &nbsp;</p>
<p>Nevertheless, this story, and thought experiments derived from it, challenge our conceptions of moral responsibility and free will. &nbsp;Let us suppose that rather than being killed, Whitman was captured. &nbsp;Let us further suppose that it was definitively proven that Whitman’s actions were caused by the tumor. Finally, let us suppose that Whitman subsequently underwent surgery which removed the malignancy and that after the surgery psychological testing determined that Whitman had no violent or antisocial impulses at all. &nbsp;That is, he was returned to his former state in which he was a loving husband and son and a responsible member of the community. &nbsp;Would we feel justified in punishing him for his crime?</p>
<p>The fundamental thesis of this book is that we all are, in a sense, like Charles Whitman. &nbsp;That is, causal factors determine all of our actions. &nbsp; None of us possess free will. &nbsp;This is not a new notion. &nbsp;Indeed, some philosophers came to this conclusion several millennia ago and it represents the views of many philosophers and scientists today. &nbsp;In the next few chapters, I will present the arguments, both old and new, to support this view, as well as dive into the ancient origins of this idea.</p>
<p>The primary project of this book, however, is what to do with this information. &nbsp;By synthesizing insights from various past and present religious and philosophical schools, I hope I can contribute to resolving that question. &nbsp;The implications of rejecting the idea of free will can be troubling. &nbsp;However, I hope to show that acceptance of this idea can actually result both in a better society and in a more joyful life. The Stoics, the Buddhists, the Confucianists, and a number of prominent philosophers understood this. &nbsp;Without free will, there can be no moral responsibility. &nbsp;Without moral responsibility, there can be no regret, remorse, guilt, or shame. &nbsp;There is no retribution. &nbsp;The criminal justice system continues to function, but in an altered, more humane way. &nbsp; We treat each other with more tolerance and compassion; we treat <em>ourselves</em> with more tolerance and compassion; life becomes more joyful. &nbsp; These are all big claims, but they are amply supported in the following chapters.</p>
<p>In what follows, I will use the word <em>freeism</em> for the belief in free will and moral responsibility and <em>freeist</em> for someone who adheres to these beliefs. &nbsp;I will define an <em>afreeist</em> as someone who does not have a belief in free will or in moral responsibility. &nbsp; I realize that these are not the most elegant terms. &nbsp;Except for the English root, I am following the convention of theist and atheist. &nbsp;A theist believes in a god or gods. &nbsp;An atheist does not have this belief. &nbsp;Thus, atheism and afreeism are both defined as an absence of belief. &nbsp;</p>
<p>There is really no scientific evidence indicating the existence of free will. &nbsp;To the contrary, there is much scientific evidence against it. &nbsp; This evidence comes from the idea of causation. &nbsp;The idea of causation is that outcomes are determined by inputs. &nbsp;On a pool table, if a cue ball of a particular size, weight, and plasticity hits another ball of a particular size, weight, and plasticity and does so at a particular angle and speed, the latter ball will move at a determined angle and speed. &nbsp;Depending on this angle and speed and the resistance of the felt on the table, etc., the struck ball may eventually fall into a pocket. &nbsp;If we know enough about the inputs, we can predict the output.</p>
<p>Almost all of us accept the idea of causation and use it for most aspects of our lives. &nbsp;We put toast in the toaster because we know that, if we push the lever down, an electrical circuit will be completed, which will provide electricity to the heating elements, which will heat up the bread causing a chemical reaction (which chemists call oxidation), resulting in a warm brown piece of toast, which we can then butter (we know that the heat will cause the butter to melt) and perhaps even put a bit a jam on. &nbsp;This will cause a pleasant sensation in our mouths as we chew and swallow our creation.</p>
<p>The idea of causation has allowed us to do some pretty remarkable things, and also some pretty awful things. &nbsp;The laws of physics embody the idea of causation. &nbsp;Scientists employ these laws to create rockets and spacecraft and to put people on the moon. &nbsp;Using causation, scientists and engineers have created smartphones and laptop computers. &nbsp; Biologists have been able to cure or vaccinate against terrible diseases, such as smallpox, polio, and many strains of influenza. &nbsp;Unfortunately, we have also exploited our knowledge of causation to create weapons of mass destruction and to wage horrible wars.</p>
<p>It seems clear that almost everybody assumes that causation applies to most events. &nbsp;Many scientists and philosophers, finding causation wherever they look, have concluded that causation is universal. &nbsp;That is, all events have causes. &nbsp;Indeed, if we knew all of the causes preceding an event, we could accurately predict that it will occur. &nbsp;This applies to toasting toast in a toaster, but also to seemingly random events like flipping a coin. &nbsp;If we knew everything about the inputs, we could predict which side the coin would land on. &nbsp;(Some scientists and philosophers make an exception for quantum mechanics, which operates at the subatomic level. &nbsp;More on this later.)</p>
<p>I note that determinism is a theory, much like evolution, or the theory of gravity. &nbsp;Like these theories, there is strong evidence to support it and no evidence that contradicts it. &nbsp;</p>
<p>Nevertheless, the idea that <em>all</em> things are caused is not universally accepted. &nbsp;I believe that it is safe to say that most people, including some philosophers and scientists, believe that humans possess free will—that is, that humans possess the ability to make a choice among various alternatives, a choice that is not dictated by strictly causal factors. &nbsp;The notion that we have free will figures in the judgments we make about people and, at times, in the consequences that we impose when people make the wrong choice. &nbsp; We consider people to be good and worthy of admiration if they make good moral choices. &nbsp;Likewise, we condemn people who make bad moral choices and sometimes ridicule people for making silly, irrational, or ill-considered choices. &nbsp; We may punish people for making socially detrimental choices. &nbsp;(For example, we may impose a jail sentence on someone who chooses to rob a bank.) &nbsp;</p>
<p>The notion that humans possess free will and that with it comes moral responsibility, is so ingrained that few people probably ever think about it. &nbsp;Nevertheless, more than two millennia ago, a number of philosophers and scientists concluded that the universe is completely deterministic, most prominently Leucippus and Democritus (proponents of the atomic theory of matter) and the Stoics. &nbsp;More recently, Baruch Spinoza, writing in the 1600s, concluded that such determinism precluded free. &nbsp;Schopenhauer and Nietzsche also rejected free will. In modern times, these doubters of free will include prominent social and physical scientists, including the late physicist Stephen Hawking, evolutionary biologist Jerry Coyne, neuroscientist Robert Sapolsky, and cognitive scientists Wolf Singer and Paul Bloom, just to name a few. &nbsp;Their argument is simple. &nbsp;If everything is caused, then the world has to unfold along a determined path. &nbsp; Choices that appear to be free really are not. &nbsp;A person may be doing what he or she desires, but these desires were caused by previous inputs. &nbsp;These inputs, in turn, were caused by other inputs. &nbsp;We can go back and back through the chain of causation. &nbsp;The result is that the choice that a person makes is caused by inputs that existed even before that person was born. &nbsp;Thus universal causation negates the possibility of free will. &nbsp; The world, and the supposed choices people make, unfolds in only one way.</p>
<p>In this book, I would like to persuade you that those philosophers and scientists who have found no evidence of free will are correct. &nbsp;In doing so, I will lean heavily on arguments that they have presented throughout history. &nbsp; (The arguments have not changed much since the days of Spinoza.) &nbsp;</p>
<p>If free will is an illusion, then it is an illusion held by many, many people. &nbsp;The question is why? &nbsp;It can be argued that the concept of free will, like the concept of a god, is an evolutionary adaptation. &nbsp;That is, some beliefs may contribute to society even if they are not true. &nbsp;A society whose members believe in free will may be more likely to survive and thrive than a society whose members do not believe in free will. &nbsp;</p>
<p>In his highly entertaining, provocative, and insightful book, Sapiens, Yuval Noah Harari, makes two major points regarding this evolutionary adaptation. &nbsp;The first is the capacity to develop and hold beliefs in fictional entities (such as the belief in a god, in a nation, or in a corporation) is an evolutionary advantage for the species homo sapiens which not only allowed the species to win out over other species of man (such as homo neanderthalensis), but also over other animals. &nbsp;In Harari’s conception, myths allowed (and allow) homo sapiens to organize and coordinate in vast numbers. &nbsp;In contrast, without myths and depending only on bonds of kinship and friendship, animals (such as apes or other species of humans) could not organize in groups greater than 150 members or so. &nbsp;Myths allowed homo sapiens to organize in vast numbers and to overwhelm their less organized competition.</p>
<p>Adapting Harari’s insight to free will, the belief in free will, and the corresponding belief in moral responsibility, may be one of those organizing myths. &nbsp;Societies whose members believe in free will may do better than those whose members do not so believe. &nbsp;The belief in free will leads to self-sanctions (guilt, remorse, regret) and social sanctions (fines, incarceration, shaming) against those who, out of their own free will, decide to engage in antisocial activity––activity that is harmful to the organization of society and thus to its survival. &nbsp;</p>
<p>(The irony of this may not be lost on some readers. &nbsp;Behavior modification is based on a causal model of behavior. &nbsp;That is, if we have the right inputs, in the form of the correct rewards or sanctions, then these will cause the right behavior. &nbsp;Yet we justify the application of rewards and sanctions through the notion of free will, which postulates that human behavior is not causally determined.)</p>
<p>Note that in Harari’s account not all myths are useful to the survival of homo sapiens. &nbsp;Myths are like viruses. &nbsp;They spread throughout society with little regard for the benefit of the species or of individuals. &nbsp;Nevertheless, if a belief contributes to the downfall of the society, it will die along with its societal host. &nbsp;Only those beliefs that benefit society will survive. &nbsp;The belief in free will may be one of these evolutionarily favored beliefs.</p>
<p>If we believe that free will is a useful myth, even perhaps an essential myth for society to organize and thrive, why not just accept the myth and move on? &nbsp;There are a number of reasons for exposing the truth. &nbsp;The first is that it is just the<strong>&nbsp;</strong>nature of science and philosophy to seek the truth, wherever it may lead. &nbsp;In such a view, the philosopher and the scientist are committed to finding the truth and let the consequences be damned. &nbsp;As such, it may be inevitable that this myth must fall. &nbsp;As Harari states:</p>
<p>[A] huge gulf is opening between the tenets of liberal humanism and the latest findings of the life sciences, a gulf we cannot ignore much longer. Our liberal political and judicial systems are founded on the belief that every individual has a sacred inner nature, indivisible and immutable, which gives meaning to the world, and which is the source of all ethical and political authority. This is a reincarnation of the traditional Christian belief in a free and eternal soul that resides within each individual. Yet over the last 200 years, the life sciences have thoroughly undermined this belief. Scientists studying the inner workings of the human organism have found no soul there. They increasingly argue that human behaviour is determined by hormones, genes and synapses, rather than by free will – the same forces that determine the behaviour of chimpanzees, wolves, and ants. Our judicial and political systems largely try to sweep such inconvenient discoveries under the carpet. But in all frankness, how long can we maintain the wall separating the department of biology from the departments of law and political science?
  <a href="#_ftn2" name="_ftnref2" title=""><em><strong>[2]</strong></em></a>
</p>
<p>If this convenient myth does fall, what then of society? &nbsp;What happens to moral responsibility, for example? &nbsp;This fear is not just a recent one. &nbsp;In response to Democritus’s view of determinism, Epicurus, in his 
  <a href="http://www.informationphilosopher.com/solutions/philosophers/epicurus/letter_to_menoeceus.html#agent-causal"><em>Letter to Menoeceus</em></a>, wrote:
</p>
<p>It is better to follow the myth about the gods than to be a slave of the "fate" of the physicists: for the former suggests a hope of forgiveness, in return for honor, but the latter has an ineluctable&nbsp;
  <a href="http://www.informationphilosopher.com/freedom/necessity.html">necessity</a>.&nbsp;
  <a href="#_ftn3" name="_ftnref3" title="">[3]</a>
</p>
<p>It is of some comfort that we have been here before. &nbsp;The concern that a loss of faith in free will could have serious societal impacts mirrors concern over the loss of faith in the existence of a god. &nbsp;If there is no belief in a god, what anchors the moral fabric of society? &nbsp;What stops people from lying, cheating, stealing, even murdering, when it is to their advantage to do so?</p>
<p>I believe that these concerns are unjustified. &nbsp;In the case of religion, a majority of the populations in many European countries have given up on a belief in a god. &nbsp;Yet, European societies continue to function. &nbsp;Indeed, one can argue that Europeans do much better than Americans in terms of social activity. &nbsp;For example, crime rates, including rates of violent crime, in continental Europe are significantly lower than those in the United States, which has a high degree of religiosity. &nbsp;This is not because Europeans have given up myths altogether. &nbsp;Harari suggests that liberal humanism, another myth, provides much of what religion did previously. &nbsp;However, losing faith in a god did not entail the loss of civilization as we know it. &nbsp;I believe that society will survive a loss of faith in free will as well.</p>
<p>And, of course, a loss of faith in free will is not inevitable. Americans, or at least a large majority of them, may never lose faith in free will. &nbsp;The United States has seemed relatively resistant to erosions of faith in a god, in spite of the success of science and philosophy in providing descriptions of the world and the place of humans in it. &nbsp;Likewise, in spite of what philosophers and scientists claim, American society will likely resist a loss of faith in free will. &nbsp;The idea of free will is so strongly-held that it seems unlikely that a majority of the population would reject it, no matter how strong the philosophical arguments or the scientific evidence.</p>
<p>But what if we could shake the belief in free will and moral responsibility? &nbsp;I believe that if the general population actually stopped believing in free will, both society and the individuals in it could be better off. &nbsp; Previously, I stated that Harari’s book Sapiens had two important theses. &nbsp;One, described above, is that myths have enabled (and continue to enable) humans to coordinate activity in great numbers, thus overwhelming other species. The second great thesis of Harari’s book, however, is that belief systems that may make the species more successful (the belief in a god, nationalism, liberal humanism, free will), do not necessarily make the <em>individuals</em> in those societies happier or better off. Therefore, while society may thrive, individuals bear the brunt of the myth.</p>
<p>I believe that humans, as a species, no longer need the myth of free will to survive and thrive. &nbsp; Furthermore, the belief in free will, while perhaps helping humans to proliferate and dominate in the past, can actually make individuals unhappy. &nbsp; I believe that losing the faith in free will would therefore make people better off. &nbsp;I believe this to be true for three related reasons: &nbsp;</p>
<ul>
  <li>Jettisoning the notion of free will can lead to the population supporting and implementing government policies that are both more humane and more effective. &nbsp;This applies particularly in the area of criminal justice, but also to many other areas of government policy. &nbsp;</li>
  <li>A personal philosophy that rejects free will can induce us to act more generously towards other people in our personal lives. &nbsp;That is, our personal behavior towards each other will improve. &nbsp;In particular, we will become more tolerant and more accepting of other people, their life situations, and their actions. &nbsp;We all will benefit. &nbsp;</li>
  <li>A personal philosophy that rejects free will can improve our attitude towards ourselves by mitigating feelings of guilt, regret, remorse, and self-blame, all of which are impediments to a joyful life, thereby promoting self-acceptance. &nbsp;</li>
</ul>
<p>In all, accepting the world the way it is, accepting that there is no free will, completely changes how we look at ourselves and at other people. &nbsp;It affects what we believe is good in the world. &nbsp;The change is profound. &nbsp;I argue that it is profoundly good. If taken seriously, this idea changes the world for the better. &nbsp;</p>
<div id="ftn1">
  <p>
    <a href="#_ftnref1" name="_ftn1" title="">[1]</a> Sapolsky (2017) 33. &nbsp;
  </p>
</div>
<div id="ftn2">
  <p>
    <a href="#_ftnref2" name="_ftn2" title="">[2]</a> Harari, Yuval Noah. Sapiens (pp. 305-306). Harper. Kindle Edition
  </p>
</div>
<div id="ftn3">
  <p>
    <a href="#_ftnref3" name="_ftn3" title="">[3]</a> 
    <a href="http://www.informationphilosopher.com/solutions/philosophers/epicurus/letter_to_menoeceus.html#agent-causal"><em>Letter to Menoeceus</em></a>, 134. &nbsp;(Need better citation.)
  </p>
</div>
</template>

<script>
// @ is an alias to /src
export default {
  name: 'handbook',
};
</script>