<template>
  <div id="Origins" class="TopicExplanation">
    <div class="TopicHeading">The Origins of Afreeism</div>
    <p>Afreeism has deep roots. The first foundations for afreeism were laid four thousand years ago when thinkers began to conclude that the universe was governed by universal rules. Stent (2002) reports:</p>
    <p>By the eighteenth century BCE the Sumerians had developed the idea that Marduk - patron god of Babylon - had ordained explicit natural laws whose obeisance by nature generated cosmic order out of cosmic chaos.</p>
    <p>In the Sumerian conception, these natural laws come from a god. The next step in this evolution of ideas occurs when the gods themselves become subject to the laws of nature.</p>
    <p>Two pre-Socratic philosophers, Leucippus and Democritus exemplify this approach. About Leucippus, we know almost nothing. (Some scholars even doubt his existence.) What we know about the ideas of Leucippus come from his student Democritus and even these come to us indirectly, given that only fragments of the writings of Democritus (which were said to be extensive) survive. Rather we must look to the descriptions of his ideas given by philosophers who were contemporaries (or near-contemporaries) of his.</p>
    <p>Leucippus and Democritus are best known for their atomic theory of matter. In essence, they wanted to replace explanations of the world based on the gods with one based on causation. All things, in their system, are composed of atoms. Atoms had different properties (that is, there were different types of atoms) and these properties determined the properties of the substances that were made up of these atoms. Laws, not the gods, governed the interaction among atoms. Leucippus is reported to have stated,</p>
    <p style="margin-left:20px;">Nothing happens in vain, but everything from reason and by necessity.</p>
    <p>This is perhaps the earliest known expression of causal determinism in western thought. Leucippus and Democritus were not trying explicitly to present an argument against free will. Rather, they wanted to remove the role of the gods in the unfolding of events. Nevertheless, by expounding a model of determinism, they put free will into question.</p>
    <h2>Plato (Socrates) and Aristotle</h2>
    <p>Plato, who expressed most of his ideas through the Socratic dialogs, did not directly discuss the problem of free will in a deterministic universe. Indeed, he did not discuss determinism at all. Plato did, however, have a conception of freedom. For Plato freedom involved self-control. Someone who exercises self-control over her emotions and her base instincts is exercising freedom. Someone who is slave to her passions is not free. Someone who is governed by reason is free. Note that under Plato’s conception of freedom, if a decision is made through reason, it is free, even if the decision is completely determined. In other words, Plato has chosen a definition of freedom that is compatible with a deterministic universe. This notion that decisions can be simultaneously free and determined has been picked up by modern-day compatibilists.</p>
    <p>Aristotle (384BCE – 322BCE) made a number of contributions to the ideas of determinism and free will. First, Aristotle did not believe that all events were caused. He posited the idea of random events. Therefore, Aristotle provided a building block for stochastic determinism. Nevertheless, Aristotle believed in free will and moral responsibility. He suggested that events are 1) caused, 2) random, or 3) up to us. This tertium quid (third thing) comprises events that are of our own free will, and which in turn result in moral responsibility. It is unclear, however, whether Aristotle was a compatibilist or a libertarian. That is, Aristotle could be saying that certain things are up to us even if they are caused or random. For Aristotle, things that are up to us are those actions that are the result of our moral character, even if our moral character is determined. That would make Aristotle a compatibilist, because he just redefines free will in a way that does not conflict with determinism. Many modern-day compatibilists see Aristotle in this light.</p>
    <p>Another reading of Aristotle, however, is that he is saying that things that are up to us are neither caused nor random but rather come from within. This would make Aristotle a libertarian. Which view Aristotle supported is unimportant to the arguments today. We can leave this debate to the historians of philosophy.</p>
    <h2>Epicureanism and Stoicism</h2>
    <p>The Greek philosopher Epicurus (341BCE – 270BCE) founded Epicureanism. Epicureanism is best known for teaching that the pursuit of pleasure is the greatest good. Epicurus adopted Democritus’s atomic theory of matter, Democritus’s atheism, and Democritus’s determinism. However, similar to Aristotle, Epicurus modified Democritus’s determinism by adding the idea of randomness (stochastic determinism) to Democritus’s atomic theory of matter. He postulated that in the movement of atoms, some atoms could “swerve” randomly. Thus, he rejected the notion of causal determinism in favor of stochastic determinism. Epicurus seemed to understand that causal determinism was a threat to free will and moral responsibility. By rejecting causal determinism in favor of stochastic determinism, Epicurus sought to remove one impediment to free will and seemed also to suggest that these swerves opened up the possibility of moral responsibility. Yet, Epicurus ultimately realized that stochastic determinism does not lead to moral responsibility any more than causal determinism does. Ultimately, Epicurus adopts Aristotle’s view that there must be a third way:</p>
    <p style="margin-left:20px;">. . . some things happen of necessity, others by chance, others through our own agency. . . necessity destroys responsibility and . . . chance or fortune is inconstant; whereas our own actions are free, and it is to them that praise and blame naturally attach.</p>
    <p>Lucretius (99–55 BCE), a Roman follower of Epicurus believed that randomness enabled free will although we have no explanation from him on how it might do so.</p>
    <p>Stoicism was a competing school of thought to Epicureanism. Zeno of Citium (c. 336–262 BCE), the founder of Stoicism, postulated a strictly deterministic universe. According to Zeno,</p>
    <p style="margin-left:20px;">It is impossible that the cause be present yet that of which it is the cause not obtain.</p>
    <p>The Stoic leader Chrysippus (279 – ~ 206 BCE) adopted Zeno’s view that events are caused, but also stated that this is not incompatible with moral responsibility. A person is morally responsible, he claimed, if the cause of his or her action is internal to him or her. That is, if there are no compelling external forces at the time of the decision causing someone to act in a specific way, and when the act is determined by internal desires and reasoning, then the person can be held to be morally responsible. This holds even if the internal desires and reasoning had been determined by a prior chain of causation. In our terminology, Chrysippus was a semicompatibilist.</p>
    <p>The Roman Stoic Cicero (106 – 43 BCE) was also a thoroughgoing determinist:</p>
    <p style="margin-left:20px;">By fate, I mean what the Greeks call heimarmen an ordering and sequence of causes, since it is the connection of cause to cause which out of itself produces anything. Consequently nothing has happened which was not going to be, and likewise nothing is going to be of which nature does not contain causes working to bring that very thing about. This makes it intelligible that fate should be, not the fate of superstition, but that of physics, an everlasting cause of things why past things happened, why present things are now happening, and why future things will be.</p>
    <p>To summarize, a number of the philosophers of antiquity realized the deterministic nature of the universe. Some postulated that the universe was causally deterministic while others postulated that the universe was stochastically deterministic. They thus laid the foundations for afreeism. None (that we know of), however, were willing to take the next logical step, that of discarding the notions of free will and moral responsibility. This will be left to later philosophers.</p>
    <h2>Christian Thought</h2>
    <p>After the fall of Rome and the beginning of the Middle Ages, much of the philosophizing in the west on free will fell to Christian and Jewish theologians. Christian theologians had two problems with their conception of God. One was that God was supposedly both omnipotent and benevolent. If so, why did he permit evil to happen? This problem actually predates the Christians. Epicurus wrote:</p>
    <p>The gods can either take away evil from the world and will not, or, being willing to do so, cannot; or they neither can nor will, or lastly they are both able and willing. If they have the will to remove evil and cannot, then they are not omnipotent. If they can, but will not, then they are not benevolent. If they are neither able nor willing, then they are neither omnipotent nor benevolent. Lastly, if they are both willing and able to annihilate evil, how does it exist?</p>
    <p>Free will solved this problem. Humans had the ability to choose good over evil of their own free will. Evil existed only if a person chose evil. Augustine defended this view. Augustine argued that free will is necessary for good, since humans could not do good without free will. Unfortunately, because of the fallibility of humans, free will also results in evil. Thus, in order to have good, we must accept that there will be evil. (The idea that evil is necessary for good will be taken up later by Leibniz.)</p>
    <p>Unfortunately, the Christian view of their god had another problem, the omniscience of God. Omniscience implies determinism. If God knows in advance everything that is going to happen, including knowing every choice a human will make in the future, then everything must be determined. Augustine seemed to realize that divine foreknowledge was equivalent to determinism. He wrote:</p>
    <p style="margin-left:20px;">This is the predestination of the saints, nothing else: plainly the foreknowledge and preparation of God’s benefits, by means of which whoever is to be liberated is most certainly liberated.</p>
    <p>In other words, those who would be saved, were saved. (And those who would be damned, were damned.) Augustine resolved this conflict in the way that modern day compatibilists do. He redefined free will. Free will was acting according to one’s desires, even if those desires were completely determined, as they must be since God also knows all past, present, and future desires. By defining free will in this way, divine foreknowledge does not conflict with free will.</p>
    <p>This was not the only Christian view of the time. Pelagius, for example, did not believe in predestination. Rather, humans (with the help of God), could freely choose to be saved. How this could be reconciled with divine foreknowledge is not clear. Augustine forcefully attacked this view and it was eventually condemned by the church.</p>
    <p>Thomas Aquinas’s views on free will are similar to those of Augustine. That is, he accepted both divine foreknowledge and free will and argued that they were not inconsistent. Free will consists of using our rationality to make decisions, guided by moral values. This, he believes, is consistent with God knowing exactly what we will choose.</p>
    <h2>Jewish Thought</h2>
    <p>In Judaism, free will was and is a central tenet:</p>
    <p style="margin-left:20px;">Free will is granted to all men. If one desires to turn himself to the path of good and be righteous, the choice is his. Should he desire to turn to the path of evil and be wicked, the choice is his.</p>
    <p>Nevertheless, by the time of the first century AD there were a variety of views:</p>
    <p style="margin-left:20px;">In his treatise, The Antiquities of the Jews, Josephus noted that the three sects differ in their opinions regarding the causation of human actions. The Essenes affirmed that fate determines all actions, and that nothing befalls mankind but what is determined by fate. They therefore rejected the role of free will in the causation of human actions and accepted the view that became known as 'determinism.'</p>
    <p>The Sadducees held that fate plays no role in human affairs, there being no such thing as fate in the first place. They supposed that all our actions are within our control, so that our own righteousness is the cause of our doing what is good and that we are driven by our own folly to doing what is evil. Hence Sadducees believed in free will.</p>
    <p>Finally, the Pharisees ascribed the cause of all human actions to fate. Yet they allowed that acting according to what is right or what is wrong is mainly within our own power, even though fate plays some causative role in every action. The Pharisees' argument regarding the compatibility of fate (and God's foreknowledge of it) with the exercise of human free will was adopted some 300 years later by St. Augustine.</p>
    <p>Later Jewish scholars recognized the conflict between free will and divine foreknowledge. Maimonides, who was born c. 1135 CE, was well aware of the problem, but argued that free will was compatible with divine foreknowledge. The error in thinking otherwise was equating knowledge of God with knowledge of humans. Just as God has a different existence than humans, God’s knowledge is somehow different than human knowledge. If a person absolutely were to know with complete accuracy that something will happen, this forecloses the possibility of anything else happening. Thus, there is no free will. However, this is not true of God’s knowledge. God’s knowing that something will happen does not foreclose the possibility of something else happening, even though something else will not happen.</p>
    <p>Other Jewish writers did not accept this explanation. Gersonides (Levi ben Gershon) (1288-1344) concluded that free will precludes God’s knowing that something will definitively happen. Rather, God’s perfect knowledge extends to knowing the possibilities of events subject to human will, but not to the outcomes:</p>
    <p style="margin-left:20px;">To affirm that God knows the possible only as possible is not detracting from His supreme intelligence, for to know things as they are means to know them well (Milḥamot, iii. 106).</p>
    <p>Ḥasdai Crescas (1340-1410), on the other hand, accepts determinism and the idea that, when considered in the context of the universe, humans have no ability to do other than what causation dictates. Yet the Torah speaks of free will and thus there must be some conception of free will that is compatible with determinism. The Jewish Encyclopedia describes Crescas’s view thusly:</p>
    <p style="margin-left:20px;">Crescas, therefore, concludes that human will is free in certain respects, but limited in others. Will acts as a free agent when considered alone, but operates by necessity when regarded in relation to the remote cause; or will operates in freedom, both per se and with regard to the provoking cause, but it is bound if analyzed with reference to the divine omniscience. Man feels himself free; therefore he is responsible, and must be rewarded or punished.</p>
    <p>In short, most Christian and Jewish thinkers needed the idea of free will in order to solve the problem of evil. Yet they also had to confront the idea that free will is inconsistent with divine omniscience. With free will one can explain evil but not omniscience. Without free will one can explain omniscience but not evil. This tension has never been resolved.</p>
    <h2>Buddhism, Confucianism and Taoism</h2>
    <p>Because Buddhism, Confucianism, and Taoism had no conception of a deity, they did not have to confront the problem of how evil could exist with an all-powerful and all-good god. They therefore did not have to resort to free will as the solution to this problem. As a result, free will is not a central tenet of any of these schools of thought. We can thus perhaps learn something about behavior in a world without free will by examining these traditions.</p>
    <p>Buddhism was founded by Siddharta Gautama. There is some dispute over when he lived, some dating his birth as early as the 560s BCE and some dating his birth about a century later. Confucius was probably born around 550 BCE. Lao Tzu, the purported founder of Taoism, may have been born anywhere from the sixth century to the fourth century BCE, although some scholars doubt his existence at all. Again, none of these three belief systems hypothesize the existence of a god. Buddha, for example, rejected the idea of a god, because he believed it was inconsistent with the existence of evil and suffering. Rather these belief systems consisted of methods and ideas about how to live. Buddhism focused on suffering and the problem of how to live with it and mitigate it. This was approached through the Eight-Fold Path. Confucianism and Taoism referred to their paths as the Tao (“The Path”), although with different emphases.</p>
    <p style="margin-left:20px;">The main difference between the Tao of Confucianism and the Tao of Taoism is that Confucianism stresses the Tao of non-natural human society while Taoism stresses the Tao of natural phenomena. Thus the humanistic Sacred Way of Confucianism, being concerned with the political order and the practical life of the person, tries to deal with the problems inherent in social relationships. It prescribes social norms and moral precepts, for which the ways of nature are of little relevance. The natural Sacred Way of Taoism, by contrast, is a transcendental moral philosophy, whose main relevance is for the person's inner life rather than for her social relations.</p>
    <p>Although Buddhism does not address the issue of free will, its writings do evidence a deterministic worldview. In fact, its view of causation is so thoroughgoing that it eschews boundaries and rather conceives of the universe as a vast seamless causal web. Indeed, Buddhism’s denial of self rejects the boundary between persons and the rest of the universe. Its moral prescriptions flow from this worldview. Buddhism rejects anger and retribution as valid reactions. Meditation is one means of overcoming these emotions.</p>
    <p>Confucianism, although its emphasis differs from that of Buddhism, also rejects both free will and retribution as a justification for punishment.</p>
    <p style="margin-left:20px;">. . . Confucius did not view the moral life as freely willed choices . . . These problems do not exist for Confucius because he does not believe that moral decisions involve any choice in the first place. Classical Western morality embedded in the Greco-Judeo-Christian tradition regards punishment as a retributive response to past moral wrongdoing. . . . This was not Confucius' view of the function of punishment, because he lacked the concept of morally responsible agents. He shared the view generally prevalent in Ancient China (and among the strain of Western moral philosophers inspired by Aristotle), that punishment serves as a utilitarian deterrent for the commission of future crimes, rather than as a just retribution to erase guilt for past crimes. . . . According to the Confucian view, the proper response to a failure to conform to the prescribed ritual order . . . is not guilt for having made a blameworthy autonomous choice, but self-education to remedy a deficiency in one's moral development.</p>
    <p>Because Confucianism provides a rationale for punishment that is independent of free will and moral responsibility, it addresses a key concern of afreeism. How can we punish in the absence of moral responsibility? We examine this in greater depth in Chapter 8.</p>
    <p>Finally, Taoism also conceives of nature as a system of which humans are a part. Taoism asserts that we have a will but is silent as to whether that will is free.</p>
    <h2>Renaissance, Enlightenment and Beyond</h2>
    <p>During the Renaissance and the Enlightenment, the issue of free will passed from the churchmen back to the philosophers. These philosophers were less concerned with the problem of evil and more concerned about how free will could be reconciled with the deterministic universe for which the new science was contributing additional evidence. Thomas Hobbes (1588-1779) was perhaps the first “modern” compatibilist. Hobbes believed that everything was the result of a web of causes, even the choices of humans.</p>
    <p style="margin-left:20px;">That which I say necessitates and determinates every action is the sum of all those things which, being now existent, conduce and concur to the production of the action hereafter, whereof if any one thing were wanting, the effect could not be produced. This concourse of causes, whereof every one is determined to be such as it is by a like concourse of former causes, may well be called the decree of God.</p>
    <p>Hobbes believed that God was the original cause. God set the universe in motion. God, is uncaused, possesses free will. Everything else, however, including human actions, is caused.</p>
    <p>Because of this determinism, Hobbes did not believe that the will is free, but he did believe that an act is free if there are no external impediments. However, because all decisions are determined, Hobbes did not believe that a person could ever be blameworthy. He did believe that there were moral obligations and that these moral obligations could cause human action. He also believed that punishment was justified by deterrence. As such, Hobbes was perhaps the first “modern” afreeist.</p>
    <p>In contrast, Hobbes’s contemporary, the French philosopher René Descartes (1596-1650) is perhaps the first “modern” libertarian. Descartes is also the modern originator of the mind-body problem. (Plato had a version of this in his conception of this dualism. ) That is, Descartes divided reality into body (the physical world) and mind (thoughts). The physical world was deterministic. Free will exists in the mind. The mind can affect the physical world.</p>
    <p style="margin-left:20px;">Descartes . . . believed that if the freedom of the human being is to be preserved, the soul must be exempt from the kind of deterministic laws that rule over the material universe.</p>
    <p>Thoughts were somehow exempt from the laws of physics and were not part of the physical world. Because of this, humans have the ability to choose between good and evil and are morally responsible.</p>
    <p>Baruch Spinoza (1632-1677) was a thoroughgoing determinist. Although he couched his determinism in theism, Spinoza’s God was in effect nature. Human action is completely determined, even though it may not seem so to humans.</p>
    <p style="margin-left:20px;">Nothing in the universe is contingent, but all things are conditioned to exist and operate in a particular manner by the necessity of the divine nature.</p>
    <p style="margin-left:20px;">. . . all things . . . flow from the same necessity; in the same way as from the nature of a triangle it follows from eternity and for eternity, that its three interior angles are equal to two right angles.</p>
    <p style="margin-left:20px;">. . . men think themselves free inasmuch as they are conscious of their volitions and desires, and never even dream, in their ignorance, of the causes which have disposed them so to wish and desire.</p>
    <p>Spinoza did not believe in free will, but he did believe in a deterministic sort of freedom. Freedom was being free of one’s passions and acting true to one’s nature. (This is very Platonic.) This is accomplished through replacing a desire for things (which we cannot control) with a desire for the knowledge and understanding of God, that is, of nature. Because of his determinism, Spinoza did not believe in many of the virtues of his day. To Spinoza, virtues are those qualities that flow from reason. Vices flow from the passions. Guilt, repentance, pity, etc., flow from the passions and thus are not virtues. Freeing oneself of these destructive impulses is possible if one understands the deterministic nature of the universe. At the end of Part II of The Ethics, he states that his deterministic philosophy . . .</p>
    <p style="margin-left:20px;">. . . “teaches us to hate no one, to disesteem no one, to mock no one, to be angry at no one, to envy no one . . .”</p>
    <p>Spinoza’s philosophy leads him to argue for religious tolerance and freedom of speech. In addition, because the universe is causal, and because we are ourselves causes, if we want to effect change, we should increase our understanding of this universe.</p>
    <p>Spinoza’s ideas were so radical for his day that he was excommunicated from his Jewish community in Amsterdam. (The excommunication probably had more to do with the community not wanting to have the Dutch authorities come down on it. Spinoza’s Jewish community comprised Portuguese refugees from the Spanish/Portuguese Inquisition and thus probably felt vulnerable in Protestant Netherlands, even though the authorities in the Netherlands were relatively tolerant for their day.)</p>
    <p>Spinoza’s determinism and ethics come very close to the afreeism that this book advocates, and we will discuss some of these ideas in later chapters.</p>
    <p>In the meantime, other philosophers continued to argue for the existence of free will. An example is Gottfried Wilhem Leibniz (1646-1716). Leibniz was a compatibilist in that he believed that free will was compatible with God’s ability to know everything that will happen in the future. Because God knows how everything will unfold, humans cannot do anything that contradicts this knowledge. Thus, everything is determined. Nevertheless, humans do deliberate and, on the basis of this deliberation, make decisions. They therefore have sufficient free will for moral responsibility.</p>
    <p>On the question of evil, Leibniz takes a slightly different approach than that of the Christian and Jewish theologians discussed above. Leibniz believed that God did not necessarily desire evil, but that evil was necessary for harmony. In other words, even God was constrained by nature. He had to choose to create a world among various possible worlds. Famously, Leibniz postulated that, given these constraints and the goodness of God, God created the “best of all possible worlds.” Given his view on evil, Leibniz did not require the concept of free will to solve the problem of evil. Nevertheless, Leibniz did believe in a compatibilist form of free will and moral responsibility.</p>
    <p>Among the British empiricists, John Locke (1632-1704) did not directly confront the issue as to whether the will could be free in a deterministic universe. Locke’s conception of freedom is the ability to do what the will dictates:</p>
    <p style="margin-left:20px;">Freedom of action, on Locke’s account, is a matter of being able to do what one wills and being able to forbear what one wills to forbear. . . [T]he mere fact (if it is a fact) that our actions are determined by the laws of nature and antecedent events does not threaten our freedom with respect to their performance. As Locke makes clear, if the door to my room is unlocked, I am free with respect to the act of leaving the room, because I have the ability to stay or leave as I will. It is only when the door is locked, or when I am chained, or when my path is blocked, or something else deprives me of the ability to stay or leave, that I am unfree with respect to the act of leaving.</p>
    <p>Although Locke does not discuss the tension between free will and determinism directly, he does provide the foundation for the compatibilist theories of Hume and later philosophers.</p>
    <p>Bishop George Berkeley (1685-1753) was a libertarian who believed that will originated nondeterministically within persons. The decisions of a person, while influenced by the environment and subject to reasoning, were not deterministically caused. That is, the person had the ability to choose among alternatives. Berkeley never explains why humans are somehow exempt from the laws of nature.</p>
    <p>David Hume (1711-1776) believed that all actions were caused. Nevertheless, he adopts the compatibilist strategy of defining an act as free if it was caused by the desires of the actor. That is, even though the actor could not do otherwise (because causal factors determined the actor’s desires), there is nevertheless free will and moral responsibility. Similar to other compatibilists, Hume never explains why actions that had to happen can be the basis of moral responsibility.</p>
    <p>Immanuel Kant (1724-1804) dismissed Hume’s compatibilist approach to free will, calling it a “wretched subterfuge.” Kant believed that true freedom had to be “entirely independent of natural law . . . ”</p>
    <p style="margin-left:20px;">Dividing the world into one of natural causality, ruled by the laws of nature, and a noumenal world governed by freedom and ruled by moral law, Kant solves the problem of free will by restricting it to the noumenal world.</p>
    <p>Because Kant believes that the noumenal self is not subject to the rules of causation, Kant is a philosophical libertarian. As with other libertarians, Kant never gives a convincing account as to why humans are somehow exempt from the laws of nature. It is indicative of the power of the illusion of free will that even a brilliant thinker such as Kant could not conceive of a world without it and would turn to almost magical thinking (the creation of a mysterious noumenal world) in order to justify it.</p>
    <p>Against this almost mystical conception of human actions, the Enlightenment was producing a growing belief in science and the causal nature of the universe. Pierre-Simon Laplace (1749-1827) was one of the most thoroughgoing advocates of the deterministic universe. Laplace was a mathematician and scientist of great accomplishment. As a mathematician, he is known for the Laplace Transform, the Laplace Equation, and the Laplacian Differential Operator. He provided a basis in calculus for classical mechanics, studied nebulae, and proposed the existence of black holes. He pioneered and promoted the Bayesian approach to probability.</p>
    <p>For our purposes, Laplace is known for Laplace’s Demon, a description of determinism. He wrote:</p>
    <p style="margin-left:20px;">We ought then to regard the present state of the universe as the effect of its anterior state and as the cause of the one which is to follow. Given for one instant an intelligence which could comprehend all the forces by which nature is animated and the respective positions of the beings which compose it - an intelligence sufficiently vast to submit these data to analysis - it would embrace in the same formula both the movements of the largest bodies in the universe and those of the lightest atom; for it, nothing would be uncertain and the future, as the past, would be present to its eyes.</p>
    <p>The “intelligence” that Laplace refers to has become known as Laplace’s Demon. In Laplace’s deterministic universe, there is no room for free will, since everything unfolds deterministically. (Less known, the scientist Roger Joseph Boscovich presented a nearly identical view 50 years earlier. )</p>
    <p>Indeed, there is no randomness in Laplace’s universe. (Consistent with Laplace’s Bayesian approach to probability, all apparent randomness comes from a lack of knowledge.)</p>
    <p>The nineteenth century witnessed additional developments. Inquiries turned to the workings of the mind. Schopenhauer (1788-1860) conceived the will as a subconscious force that derives from the character of the individual. This will is free in the sense that the will determines actions. Yet the will itself, because it is subconscious and because it is determined by the character of the individual, is beyond the conscious control of the individual. Thus, freedom of choice is just an illusion. Nevertheless, because the will derives from the character of the individual, there exists moral responsibility. By imposing moral responsibility, we can influence the choices that the will makes. (However, Schopenhauer was skeptical as to whether punishment could affect character and the will itself.)</p>
    <p>Nietzsche (1844-1900) picks up Schopenhauer’s idea that actions follow from an unconscious will. Nietzche does not follow Schopenhauer’s characterization of the will as free. Rather, he uses this idea to characterize human actions as a product of strict determinism. (This difference with Schopenhauer may just be semantic, since Schopenhauer did not believe that human actions were at all free.) The appeal to the unconscious is Nietzsche's main argument against the freedom of the will. We cannot control our unconscious states (we do not have access to them) and thus we cannot control our will. Our will determines our actions. Nietzsche also argued that nothing is the cause of itself, and since freedom of the will would imply something causing itself, it follows that freedom of the will is absurd. Therefore, our actions are not free</p>
    <p>Note that this view eliminates compatibilist conceptions of free will. Compatibilists posit that free will is doing what one wants, even if what one wants is causally determined. For Nietzche, however, one does not consciously do what one wants. The will operates unconsciously.</p>
    <h2>Afreeism in Historical Context</h2>
    <p>Musings on causation, determinism, free will and moral responsibility have continued apace throughout the twentieth century and into the twenty-first century. Academia.com, a portal for research papers lists (at the time of this writing) over 70,000 articles under the rubric “free will and determinism.” However, the landscape has not changed much. Some continue to argue that humans are somehow exempt from the laws of nature and causation and are capable of making choices that are neither caused nor random. Others have conceded that the universe is deterministic and that all choices are caused but argue that free will nevertheless exists. They accomplish this by changing the definition of free will. They then claim that this newly-defined free will implies moral responsibility. However, they never adequately explain how someone can be morally responsible for acts that simply had to happen. Finally, there are those who understand that the deterministic nature of the universe means that there is neither free will nor moral responsibility. This is the afreeist understanding.</p>
    <p>Again, afreeism is not a new idea. Indeed, the Greeks of antiquity understood that that the universe was causally or stochastically deterministic. The nontheistic traditions of Buddhism and Confucianism discarded the notion of free will and developed moral practices that were independent of it. In the West, a number of philosophers, such as Thomas Hobbes and Baruch Spinoza, rejected the notion of moral responsibility in favor of alternative rationales for punishment. Since discarding the notion of free will has implications in terms of social policy, in how we treat other people, and in how we view ourselves, we should try to glean everything we can from those who first confronted these issues. We will be returning to some of these ideas in future chapters.</p>
    <p></p>
    <p></p>

    <p>
      <a href="#Back">Back to top.</a>
    </p>
  </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: "Origins"
};
</script>
<style scoped>
</style>
